name: Docker HK-Comp Image CI

on:
  push:
    branches: [main]
    tags: ['*']
    
jobs:

  build:

    runs-on: ubuntu-latest

    steps:
   
    - name: docker login
      run: docker login ghcr.io -u ${{ github.actor }} -p ${{ secrets.TOKEN }}

    - uses: actions/checkout@v2
    - name: Build the Dependencies1 Docker image
      run: docker build . --file Dockerfile --tag ghcr.io/hyperk/hk-comp:latest
        
    - name: push docker image
      run: docker push ghcr.io/hyperk/hk-comp:latest